name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: stylua
        uses: JohnnyMorganz/stylua-action@76fd70c03e6340ceaf673366712db9b20560b402 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: v2.5.2
          args: --check lua plugin tests

      - name: Install selene
        uses: baptiste0928/cargo-install@f204293d9709061b7bc1756fec3ec4e2cd57dec0 # v3.4.0
        with:
          crate: selene
          version: "0.31.0"
          locked: true

      - name: selene
        run: selene lua plugin tests

  test:
    name: Test (${{ matrix.neovim }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        neovim: [stable, nightly]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Neovim
        uses: rhysd/action-setup-vim@febef33995d6649302e9d88dda81e071b68f16a7 # v1.6.1
        with:
          neovim: true
          version: ${{ matrix.neovim }}

      - name: Run tests
        run: make test
